### ISSUE TITLE
Can't target @p

### ISSUE THREAD

**Issue by jasminnancy** [mrgeneralq/SaveRod#11]
I would like to give `@p` the SaveRod in a command block but keep getting the error `Invalid Player`
Can you fix this?

**Comment by mrgeneralq** [comment]
Hello @jasminnancy 

Thank you for reporting the issue. The problem seems to be related with how Spigot is handling the command blocks. After you reached out to me in our discord, I found the following resource by md_5 that would add selectors to spigot. Currently no confirmation if this actually resolves the issue.

Plugin: https://www.spigotmc.org/resources/selecteverywhere.64475/
Source solution: https://hub.spigotmc.org/jira/browse/SPIGOT-4193?attachmentOrder=desc

Please let me know in discord if this solution resolved your issue.

Kind regards

Quinten

**Comment by mrgeneralq** [comment]
Solution confirmed working. Code might be implemented in future release
